### ISSUE TITLE
auto generated test file problem

### ISSUE THREAD

**Issue by darluc** [box/TestScribe#2]
I followed your instructions in your Evaluator Guide, and got a test file generated in directory like this one: 
> /Users/darluc/Documents/Codes/TestScribe/tests/Unit/Users/darluc/Documents/Codes/TestScribe/tests/_fixture/_input/TestEarlyDemoGenTest.php

As you can see, maybe it's not in the place it was supposed to be.

**Comment by HappyRay** [comment]
Hi @darluc,

Thanks for trying the project and giving me the feedback.

This is to be expected since the source-root directory parameter used by the convenient launch script is assumed to be src. The examples are placed under tests directory instead. I used the script despite this problem because I wanted the example to be closer to what people would use to test their own production code.

Sorry about the confusion.

----

Given your feedback, I've updated [the evaluator's guide](https://github.com/box/TestScribe/wiki/User-Guide#evaluator-guide) with the correct parameter.

Here is the output I got:

	TestScribe (master) $ php bin/test_scribe.php generate-test --test-source-root=tests/Unit --source-root=tests --bootstrap=tests/_fixture/bootstrapForTest.php tests/_fixture/_input/TestEarlyDemo.php computeAndGetResultMsg

	Starting the test run. Version ( 0.3.2 )
	Type character h for help when prompted for an input value.

	Testing the method ( computeAndGetResultMsg ) of the class ( \Box\TestScribe\_fixture\_input\TestEarlyDemo ).
	Enter the name of the test. Press enter to use the default test name ( test_computeAndGetResultMsg ).
	>


	Prepare to get arguments to the method ( __construct ) of the class ( Box\TestScribe\_fixture\_input\TestEarlyDemo ).

	Mocked ( \Box\TestScribe\_fixture\_input\ComplexComputation ) id ( mockComplexComputation1 ).



	Start executing the constructor.


	Finish executing the constructor.


	Prepare to get arguments to the method ( computeAndGetResultMsg ) of the class ( Box\TestScribe\_fixture\_input\TestEarlyDemo ).

	Provide the parameter ( input ), type ( int ).
	>
	-1


	Start executing method ( computeAndGetResultMsg ).


	Finish executing method ( computeAndGetResultMsg ).

	Result from this method execution is :
	Negative input ( -1 ) is provided. Only non negative input is supported.
	End of the result.

	Please verify this result and the interactions with the mocks are what you expect.

	Added a test to ( /Users/ryang/github/TestScribe/tests/Unit/_fixture/_input/TestEarlyDemoGenTest.php ).  

----

Could you give it a try again and see if the output makes more sense to you now?

I am interested in your experience with the tool so far and would appreciate any further feedback.

**Comment by darluc** [comment]
Thank you. I just started trying your fancy tool, and hope it will help me testing my code much more easily.

**Comment by HappyRay** [comment]
Thanks.
