### ISSUE TITLE
box-project.org cannot be visited

### ISSUE THREAD

**Issue by darluc** [box/TestScribe#5]
Did the domain name expire?
Please remove the link in the [Develop Guide](https://github.com/box/TestScribe/wiki/Developer-Guide)

Also 'phpunit' command is located in the vendor/bin directory, and there is no 'box.phar' in the build/ directory.

**Comment by HappyRay** [comment]
Thanks for reporting this problem. Yes, [the third party site](http://box-project.org/)'s domain name seems to have expired. I hope the developer would fix it soon.

I added a link to the alternative download site on the developer guide page. 

box.phar is not checked into build/ directory. This is the binary to be downloaded from the thirdparty website.

That said, only the project maintainers would need to download this tool once. You shouldn't be blocked because of this problem. Please let me know if it is not the case.

I also updated the dev guide to refer to the alternative PHPUnit location.

**Comment by darluc** [comment]
:100: 
I think guides should be correct, so I just made these advices.

**Comment by HappyRay** [comment]
I appreciate your help.

Because of your bug report, the guide is better.
